[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI= "false"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true